[workspace]
members = [
    "src/sdkgen",
    "src/sdkgen_core",

    # Adapters
    "src/sdkgen_adapter_openapi",

    # Emitters
    "src/sdkgen_emitter_csharp",
    "src/sdkgen_emitter_typescript"
]
